---
title: "Worksheet 2"
author: "Khylle irvgard andigan"
date: "2024-09-30"
output: pdf_document
---
```{r}
Sequence <- c("-5","-4","-3","-2","-1","0","1","2","3","4","5")

x <- 1:7 # The value is 1,2,3,4,5,6,7

seq(1, 3, by=0.2) #The value of value of X is added to 1 until it reaches the value 3

ages <- c("34", "28", "22", "36", "27", "18", "52", "39", "42", "29", "35", "31", "27", "22", "37", "34", "19", "20", "57", "49", "50", "37", "46", "25", "17", "37", "43", "53", "41", "51", "35", "24", "33", "41", "53", "40", "18", "44", "38", "41", "48", "27", "39", "19", "30", "61", "54", "58", "26", "18")

third_element <- ages[3]
ages[3]

second_element <- ages[2]
fourth_element <- ages[4]
print(c(second_element, fourth_element))

modified_ages <- ages[-c(4, 12)]
modified_ages

x <- c("first" = 3, "second" = 0, "third" = 9)
vector_names <- names(x)
selected_elements <- x[c("first", "third")]
selected_elements #Accessing x[c("first", "third")] retrieves the values associated with the names "first" and "third", which are 3 and 9, respectively.
```
```{r}
x <- -3:2

x[2] <- 0

months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
prices_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
purchase_quantity <- c(25, 30, 40, 50, 10, 45)

diesel_data <- data.frame(Month = months,  Price_per_liter_Php = prices_per_liter, Purchase_quantity_Liters = purchase_quantity)
diesel_data

expenditures <- diesel_data$Price_per_liter_Php * diesel_data$Purchase_quantity_Liters

average_expenditure <- weighted.mean(diesel_data$Price_per_liter_Php, diesel_data$Purchase_quantity_Liters)
average_expenditure

data_lengths <- rivers
num_elements <- length(data_lengths)
total_sum <- sum(data_lengths)
mean_value <- mean(data_lengths)
median_value <- median(data_lengths)
variance_value <- var(data_lengths)
sd_value <- sd(data_lengths)
min_value <- min(data_lengths)
max_value <- max(data_lengths)
```
```{r}
stats_vector <- c(num_elements, total_sum, mean_value, median_value, 
                  variance_value, sd_value, min_value, max_value)
stats_vector

data <- c(length(rivers),          
           sum(rivers),             
           mean(rivers),            
           median(rivers),        
           var(rivers),            
           sd(rivers),              
           min(rivers),            
           max(rivers))

print(data)

ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)

rowling_index <- 19
ranking[rowling_index] <- 15
pay[rowling_index] <- 90

```